### ISSUE TITLE
Any existing plans, TODO lists, etc.?

### ISSUE THREAD

**Issue by dumblob** [Osiris-Team/Simple-Calendar#1]
I wonder if you have some further undisclosed/unimplemented plans for this fork? If so, could you list them here perhaps?

Thanks!

**Comment by dumblob** [comment]
Btw. reading your major use case for tags - do you think it could be solved by a simpler feature "create new event and prefill it with a selected existing event"?

**Comment by Osiris-Team** [comment]
I have no more plans for this, and also already implemented the tags feature.
But I am open to merge any pull request.
