### ISSUE TITLE
Paid developer consulting experience opporunity

### ISSUE THREAD

**Issue by User2564** [Osiris-Team/Simple-Calendar#2]
Hi @Osiris-Team,
I hope this message finds you well.

I could not help but notice your discussion on the upstream repo.
To cut right to the chase, how would you feel about the opportunity to gain some paid developer consulting experience working on OSS Android applications?

If possible this would be via committing code to separate branches on my own fork of each application so that I may perform my own end user testing with the end goal of  submitting them back to the upstream project.

How would you wish to be credited? e.g. Tagged within the MR or as a separate document / letter.

By interest / hobby / background I am in the IT sector, but focused more on the physical / networking / security aspects.
I can appreciate how hard can be at times (to put it very very mildly) to find any work as a student let alone with one's desired industry.

Slight side note, why must Github make it nearly impossible to;
- Quickly identify how many members are in a project?
- Mark an issue as confidential.

Both are trivial to do with GitLab, at least as implemented by a service that I interact with as a part of my community developer hobby.

Looking forward to hearing from you.

Kind regards,
User2564

**Comment by Osiris-Team** [comment]
@User2564 hey that sounds great! I am currently already looking for jobs I can do while studying that are also related to IT, so this sounds like a pretty good opportunity. You can email me at osiris_support@proton.me or via direct message over Discord under ak_osiris.
